[package]
name = "l1npengtul-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26"
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = "0.3"
tree-sitter-highlight = "0.20"
handlebars = "4.3"
toml = "0.5"
seahash = "4.1"
ignore = "0.4"
tantivy = "0.18"
color-eyre = "0.6"
git2 = "0.15"
chrono = "0.4"
minify-html = "0.10"
serde_json = "1.0"
html_editor = "0.5"
bytes = "1.2"
pathdiff = "0.2"

[dependencies.tokio]
version = "1.20"
features = ["full"]

[dependencies.axum]
version = "0.6.0-rc.1"
features = ["http2"]

[dependencies.sea-orm]
version = "0.9"
features = ["runtime-tokio-rustls", "sqlx-postgres", "macros", "with-json", "with-chrono"]

[dependencies.moka]
version = "0.9"
features = ["future"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.rsass]
version = "0.25"

[dependencies.pulldown-cmark]
version = "0.9"
features = ["serde", "simd", "getopts"]

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
